### PR TITLE
Update link for fonts.gstatic.com to https

### PR DESCRIPTION
**Pull request by Twincarb**
Fix for when using the template in a pure https mode. fix for #30

### CODE REVIEW

**Comment by gsuez** [comment]
thanks!
I can`t merge, because can cause problems for users who use http - most cases ;)

Regards

**Comment by Twincarb** [comment]
I am curious under what circumstances would it cause issues, it has no reliance on the webserver that is providing the website to provide a secure connection, the request is executed by the end user browser. As far as I am aware all the major browsers provide https support.

**Comment by Twincarb** [comment]
@gsuez I have adjusted the request so it's not hardcoded to http or https please review.

**Comment by phproberto** [comment]
:+1: this will require that we recompile sass files to get latest css files. I tried to generate new css files but apparently a lot of things are changed because sass + css files are not synchronised. But that's not related to this pull request.

**Pull request merged**
